#!/usr/bin/env ruby -wKU

# Acts as the bin/main file

require "spec"



describe "Array#last" do
  
  before do
    puts "yikes!"
  end
  
  # it "should do something"
  
  it "is" do
    10.should eql(9)
  end
  
  it "should erroe!"
  
  # describe "something else entierely" do
    # it "should hopefully work"
  # end
  
end


# describe "bob" do
  # example "wowoooowo"
# end

Spec::Runner.run