#!/usr/bin/env ruby -wKU

require "spec"
# 
Dir[File.join('examples', '**', '*.rb')].each do |rb|
  require rb
end
# 
# # We cannot run tests until document is loaded (as we write to document)
Document.ready? do
  Spec::Runner.run
end

