#!/usr/bin/env ruby -wKU

require "spec"

Dir[File.join('examples', '**', '*.rb')].each { |rb| require rb }

# We cannot run tests until document is loaded (as we write to document)
Document.ready? do
  Spec::Runner.run
end
