name: Sample Controls
load: config/environment.rb
version: "1.0"
default_locale: en
resources:
  - resources/images/**/*.*
  - resources/stylehseets/**/*.*
sources: 
  - app/**/*.rb
  - config/**/*.rb
platforms:
  - w3c
  - ie8
  - ie7

# list all dependencies so we can ship them with the app (vienna is included by 
# default, so we can ommit it.)
dependencies: 
  - vienna
  
# compiler options. mostly apply to ruby, but some general
compiler_options:
  # embed images into css using data uris/mhtml
  embed_resources: true
  # output debug symbols into generated code (makes opcodes more readable)
  debug_symbols: true
  # symbol table for strings etc (saves outputting same string more than once)
  symbol_table: true
  # do we output /en.html, /fr.html or /en/index.html, /fr/index.html
  locales_in_directories: false
  # bin path - where, relative to index.html, should the .vn files be placed
  bin_path: "/"
