# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{opal}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Beynon"]
  s.date = %q{2010-01-22}
  s.description = %q{Ruby runtime for the browser}
  s.email = %q{adam@adambeynon.com}
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION",
     "docs/jarv.rdoc",
     "lib/opal.rb",
     "runtime/array.js",
     "runtime/class.js",
     "runtime/compar.js",
     "runtime/dir.js",
     "runtime/enum.js",
     "runtime/file.js",
     "runtime/gem.js",
     "runtime/hash.js",
     "runtime/init.js",
     "runtime/load.js",
     "runtime/module.js",
     "runtime/number.js",
     "runtime/object.js",
     "runtime/opal.js",
     "runtime/parse.js",
     "runtime/range.js",
     "runtime/re.js",
     "runtime/string.js",
     "runtime/variable.js",
     "runtime/vm.js",
     "runtime/yaml.js",
     "tasks/build.rb"
  ]
  s.homepage = %q{http://github.com/adambeynon/opal}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby runtime for the browser}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<vienna>, [">= 0.0.3"])
    else
      s.add_dependency(%q<vienna>, [">= 0.0.3"])
    end
  else
    s.add_dependency(%q<vienna>, [">= 0.0.3"])
  end
end

