# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vienna}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Beynon"]
  s.date = %q{2010-02-03}
  s.description = %q{Ruby compiler and runtime for the browser}
  s.email = %q{adam@adambeynon.com}
  s.executables = ["vienna", "vn-build", "vn-gen", "vn-server"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     ".gitmodules",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/.DS_Store",
     "bin/vienna",
     "bin/vn-build",
     "bin/vn-gen",
     "bin/vn-server",
     "gen/app/app.yml",
     "gen/capp/capp.yml",
     "gen/capp/capp_name/info.yml",
     "lib/vienna.rb",
     "lib/vienna/additions/cappuccino.rb",
     "lib/vienna/additions/hash.rb",
     "lib/vienna/additions/plist.rb",
     "lib/vienna/builders/base.rb",
     "lib/vienna/builders/combine.rb",
     "lib/vienna/builders/css.rb",
     "lib/vienna/builders/html.rb",
     "lib/vienna/builders/javascript.rb",
     "lib/vienna/builders/objective_c.rb",
     "lib/vienna/builders/objective_c/file.rb",
     "lib/vienna/builders/objective_c/implementation.rb",
     "lib/vienna/builders/objective_c/interface.rb",
     "lib/vienna/builders/objective_c/method.rb",
     "lib/vienna/builders/objective_c/models.rb",
     "lib/vienna/builders/objective_c/objective_c.rb.y",
     "lib/vienna/builders/objective_c/objective_c.tab.rb",
     "lib/vienna/builders/objective_c/output.rb",
     "lib/vienna/builders/objective_c/protocol.rb",
     "lib/vienna/builders/objective_c/struct.rb",
     "lib/vienna/builders/objective_c/symbol_table.rb",
     "lib/vienna/builders/plist.rb",
     "lib/vienna/builders/ruby.rb",
     "lib/vienna/builders/ruby/file.rb",
     "lib/vienna/builders/ruby/generate.rb",
     "lib/vienna/builders/ruby/nodes.rb",
     "lib/vienna/builders/ruby/objective_j/objj_ruby.rb",
     "lib/vienna/builders/ruby/ruby_parser.rb",
     "lib/vienna/builders/ruby/ruby_parser.rb.y",
     "lib/vienna/builders/vib.rb",
     "lib/vienna/builders/xib.rb",
     "lib/vienna/models/browser_project.rb",
     "lib/vienna/models/browser_runtime.rb",
     "lib/vienna/models/bundle.rb",
     "lib/vienna/models/capp_bundle.rb",
     "lib/vienna/models/cappuccino_project.rb",
     "lib/vienna/models/framework.rb",
     "lib/vienna/models/gem_bundle.rb",
     "lib/vienna/models/language.rb",
     "lib/vienna/models/new_project.rb",
     "lib/vienna/models/platforms/osx.rb",
     "lib/vienna/models/platforms/web.rb",
     "lib/vienna/models/platforms/web_app_gem.rb",
     "lib/vienna/models/platforms/web_gem.rb",
     "lib/vienna/models/plist.rb",
     "lib/vienna/models/project.rb",
     "lib/vienna/models/ruby_bundle.rb",
     "lib/vienna/rack/app_server.rb",
     "lib/vienna/rack/inflector.rb",
     "lib/vienna/rack/record.rb",
     "lib/vienna/rakefile/Rakefile",
     "lib/vienna/rakefile/rakefile.rb",
     "lib/vienna/resources/rdoc.css",
     "lib/vienna/tasks/tasks.rb",
     "lib/vienna/tools.rb",
     "lib/vienna/tools/build.rb",
     "lib/vienna/tools/clean.rb",
     "lib/vienna/tools/generate.rb",
     "lib/vienna/tools/init.rb",
     "lib/vienna/tools/server.rb",
     "platforms/README.rdoc",
     "platforms/osx/platform_window.rb",
     "platforms/web/README.rdoc",
     "platforms/web/platform/platform.js",
     "spec/spec_helper.rb",
     "spec/vienna_spec.rb",
     "test/test_vienna.rb",
     "vienna.gemspec"
  ]
  s.homepage = %q{http://github.com/adambeynon/vienna}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby compiler and runtime for the browser}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/vienna_spec.rb",
     "test/test_vienna.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

