# 
#  Rakefile
#  VRuby
#  
#  Created by Adam Beynon on 2009-10-29.
#  Copyright 2009 Adam Beynon. All rights reserved.
# 

config :all,
  
  # :sdk => 'vienna',
  :sdk => 'cappuccino',
  
  :build_prefix => 'build',
  :tmp_prefix => 'build/tmp',
  
  # :required => [:Vienna, :AppKit, :Foundation],
  
  :preferred_language => :en,
  
  # Used for the generator to insert automatic names etc
  :user_name => 'Your Name',
  :organization_name => 'My Company'
  

  # :compiler_directives => {
  # # Rendering mode (canvas or dom based). If you are not doing any drawing,
  # # then you do not have to worry about these. They are primarily used by
  # # AppKit etc to determine how to draw. Canvas is default
  # :VIENNA_RENDERING_MODE_CANVAS => true,
  # :VIENNA_RENDERING_MODE_DOM => false
  # }

config :debug,
  :compress => false,
  :build_prefix => 'build/debug',
  :tmp_prefix => 'build/tmp/debug'

config :release,
  :compress => true,
  :build_prefix => 'build/release',
  :tmp_prefix => 'build/tmp/release'