# 
#  Rakefile
#  vienna
#  
#  Created by Adam Beynon on 2009-05-19.
#  Copyright 2009 Adam Beynon. All rights reserved.
# 

config :all,
  :required => [:objc, :CoreFoundation],
  :user_name => 'Adam Beynon',
  :organization_name => 'Adam Beynon'
