# 
#  Rakefile
#  vienna
#  
#  Created by Adam Beynon on 2009-05-18.
#  Copyright 2009 Adam Beynon. All rights reserved.
# 

config :all,
  
  # build paths etc REQUIRED
  :build_prefix => 'build',
  :tmp_prefix => 'build/tmp',
  
  # Required frameworks: Cocoa includes AppKit/Foundation
  # 
  # These can be system frameworks like Cocoa etc, or custom frameworks
  # that are located in project_path/frameworks/ They are located at build
  # time, and local frameworks take presitence over system frameworks, so
  # you can modify AppKit, for example, locally just for the project and 
  # use this copy instead of chnaging the global appkit framework.
  # 
  # These can be symbols (:Cocoa) or strings "Cocoa". If more than one is
  # required, then pass an array: [:Cocoa, :MyFramework, :OtherFramework]
  :required => [:Vienna, :AppKit, :Foundation],
  
  # Preferred lnaguage: default app language to suit English.lproj
  :preferred_language => :en,
  
  # Used for the generator to insert automatic names etc
  :user_name => 'Your Name',
  :organization_name => 'My Company',
  
  # Used for inserting copyrights to the tops of files
  :copyright_notice =>
%q{Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.},

  # Pre-processor defines (for objective-c only)
  # 
  # setting a variable to true will define it, where as setting a variable to 
  # false will simply ommit it: false is the same as not defining it, but in
  # some cases it helps readability e.g. when stating rendering mode.. one 
  # should be true (canvas) when the other is false (dom). Note: Canvas
  # rendering also referes to using VML in IE as IE does not support canvas
  # (as of version 8).
  :compiler_directives => {
  # Rendering mode (canvas or dom based). If you are not doing any drawing,
  # then you do not have to worry about these. They are primarily used by
  # AppKit etc to determine how to draw. Canvas is default
  :VIENNA_RENDERING_MODE_CANVAS => true,
  :VIENNA_RENDERING_MODE_DOM => false
  }

config :debug,
  :compress => false,
  :build_prefix => 'build/debug',
  :tmp_prefix => 'build/tmp/debug'

config :release,
  :compress => true,
  :build_prefix => 'build/release',
  :tmp_prefix => 'build/tmp/release'