# 
#  Rakefile
#  vienna
#  
#  Created by Adam Beynon on 2009-05-18.
#  Copyright 2009 Adam Beynon. All rights reserved.
# 

config :all,
  
  # Required frameworks: Cocoa includes AppKit/Foundation
  :required => [:Cocoa, :AppKit, :Foundation],
  
  # Preferred lnaguage: default app language to suit English.lproj
  :preferred_language => :en,
  
  # Used for the generator to insert automatic names etc
  :user_name => 'Your Name',
  :organization_name => 'My Company',
  
  # Used for inserting copyrights to the tops of files
  :copyright_notice =>
%q{Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.}