# General options for building
# 
# main ruby file to include.
# 
# Files to be included in the build. These are not automatically required(), 
# but will be available at runtime to include if you wish.
# 
# e.g. OPAL_REQUIRED_FILES = ["twitter.rb", "my_effects.rb"]
task :options do
  begin
    require '../../../lib/vienna'
  rescue LoadError => e
    abort "You need vienna installed. Go install it: gem install vienna"
  end
  
  OPAL_BUILD_OPTIONS = {
    :main => "browser_interactions.rb",
    :require => []
  }
end

desc "Update opal runtime with newest version"
task :update => :options do
  Vienna::Opal::Project.new.update_opal!
end

desc "Build package into single .js file"
task :build => :options do
  p = Vienna::Opal::Project.new
  p.update_opal!
  p.build!
end

desc "Spawn a rack based server to host the application"
task :server => :options do
  puts "Spawn server"
end
